# The Site Configuration

theme: jekyll-theme-chirpy

lang: en

timezone: Asia/Kuala_Lumpur

title: Wilsen Kannan CPP

tagline: Make Better Packaging Everyday, Allday Long.

description: >-
  Wilsen Kannan's personal website covering packaging technology,
  sustainability

url: "https://wilsenkannan.github.io"

baseurl: ""

avatar: /assets/profile.jpeg

github:
  username: WilsenKannan

social:
  name: Wilsen Kannan
  links:
    - "https://github.com/WilsenKannan"

theme_mode: ""

toc: true

comments:
  active: false

analytics:
  google:
    id:

pwa:
  enabled: true
  cache:
    enabled: true

paginate: 10

kramdown:
  syntax_highlighter_opts:
    disable: false
